# Config format schema number
format_version: 4

###################
## Model options
model_params:

  history_num_frames: 30
  future_num_frames: 20
  filter_agents_threshold: 0.8
###################

data_generation_params:
  max_num_lanes: 15
  max_points_per_lane: 31    #equal to history_num_frames + 1
  max_lane_distance: 5
  max_agents_distance: 50
  max_num_agent: 20
  min_history: 30
  min_future: 20


###################
## Data loader options
val_data_loader:
  key: "scenes/sample.zarr"
  batch_size: 12
  shuffle: False
  num_workers: 16

train_data_loader:
  key: "scenes/sample.zarr"
  batch_size: 12
  shuffle: True
  num_workers: 16


###################
## To create MapAPI
raster_params:
  # raster image size [pixels]
  raster_size:
    - 224
    - 224
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.5
    - 0.5
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.25
    - 0.5
  map_type: "py_semantic"
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"
  filter_agents_threshold: 0.5
  disable_traffic_light_faces: False
  set_origin_to_bottom: True


###################
## Training options
train_params:
  subgraph_learning_rate: 0.001
  globalgraph_learning_rate: 0.001
  decoder_learning_rate: 0.001
  epoch: 1
  saving_path: "./save/models"
  local_rank: 0
  logging_steps: 100
  saving_steps: 1000

